plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.google.cloud.tools.jib' version '3.5.4'
    id 'org.sonarqube' version '7.5.0.8588'
    id 'jacoco'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain { languageVersion = JavaLanguageVersion.of(25) }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('test') {
    useJUnitPlatform()
}

jacoco {
    toolVersion = '0.8.15'
}

tasks.named('jacocoTestReport') {
    reports {
        html.required = true
        xml.required = true
        csv.required = true
    }
}

sonar {
    properties {
        property 'sonar.projectName', 'SpringBoot Code Coverage Demo'
        property 'sonar.exclusions', '**/generated-*/**/*'
        property 'sonar.projectKey', 'org.sonarqubeJacocoCodeCoverage'
        property 'sonar.coverage.jacoco.xmlReportPaths', layout.buildDirectory.file('reports/jacoco/test/jacocoTestReport.xml').get().asFile
        property 'sonar.host.url', 'http://ec2-15-165-232-8.ap-northeast-2.compute.amazonaws.com:9000'
        property 'sonar.sources', 'src/main/java'
        property 'sonar.tests', 'src/test/java'
    }
}

tasks.named('sonar') {
    dependsOn tasks.named('test'), tasks.named('jacocoTestReport')
}

jib {
    from { image = 'eclipse-temurin:25-jre-alpine' }
    to {
        image = '808101328892.dkr.ecr.ap-northeast-2.amazonaws.com/test'
        tags = ['sonarqube']
    }
    container {
        ports = ['8080']
        environment = [SPRING_OUTPUT_ANSI_ENABLED: 'ALWAYS']
        labels = [version: project.version, name: project.name, group: project.group]
        creationTime = 'USE_CURRENT_TIMESTAMP'
        format = 'Docker'
    }
}
