def mainDir = "Part2_Docker/Chapter02/2-jenkins-docker"
def region = "ap-northeast-2"
def ecrUrl = "808101328892.dkr.ecr.ap-northeast-2.amazonaws.com"
def repository = "test"
def deployHost = "172.31.34.15"

pipeline {
    agent any

    stages {

        stage('Pull Codes from Github') {
            steps {
                checkout scm
            }
        }

        stage('Build Codes by Gradle') {
            steps {
                sh """
                    cd ${mainDir}
                    ./gradlew clean build
                """
            }
        }

        stage('Build Docker Image by Jib & Push to AWS ECR Repository') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-key'
                ]]) {
                    sh """
                        cd ${mainDir}

                        export ECR_PASSWORD=\$(aws ecr get-login-password --region ${region})

                        ./gradlew jib \
                            -Djib.to.image=${ecrUrl}/${repository}:${currentBuild.number} \
                            -Djib.to.auth.username=AWS \
                            -Djib.to.auth.password="\$ECR_PASSWORD" \
                            -Djib.console=plain
                    """
                }
            }
        }

        stage('Deploy to AWS EC2 VM') {
            steps {
                sshagent(credentials: ['deploy-key']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@${deployHost} '
                            aws ecr get-login-password --region ${region} |
                            docker login --username AWS --password-stdin ${ecrUrl}

                            docker run -d \
                                -p 80:8080 \
                                ${ecrUrl}/${repository}:${currentBuild.number}
                        '
                    """
                }
            }
        }
    }
}